# Site settings
name: Village Sweep
slogan: Chimney And Boiler Services
url: villagesweep.org
baseurl: ""
description:
email: sparkosone@hotmail.com

# Build settings
permalink: pretty
exclude: ["node_modules", "bower_components", "font-awesome-4.5.0", "gulpfile.js", "bower.json", "package.json", "js", "frog_up.sh"]

gems:
  - jekyll-sitemap
